--- 
abstract: "[One line description of module's purpose here]"
author: Kevin Falcone  C<< <falcone@bestpractical.com> >>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Extension-ReassignOwner
no_index: 
  directory: 
    - etc
    - inc
    - t
requires: 
  Test::More: 0
version: 0.01
